obj-$(CONFIG_LYCHEE_LCD_SUN4I) += lcd.o

lcd-objs := dev_lcd.o
obj-$(CONFIG_LYCHEE_LCD_DEFAULT)  += lcd0_panel_cfg.o lcd1_panel_cfg.o
obj-$(CONFIG_LYCHEE_LCD_AINOL_AUROTA)  += lcd_bak/ainol_aurota.o lcd1_panel_cfg.o